export interface Recipe {
  name: string
  station: 'cutting_board' | 'fry_station' | 'drink_station' | 'stove'
  ingredients?: { name: string; amount: number }[]
  utensil?: string
  duration?: number
}

export const recipes: Recipe[] = [
  // Cutting Board (36 recipes) — JSON: default_duration 4s, default_output 5
  { name: 'Bread Loaf', station: 'cutting_board', ingredients: [{ name: 'Wheat', amount: 5 }], utensil: 'Whisks', duration: 4 },
  { name: 'Brown Sugar', station: 'cutting_board', ingredients: [{ name: 'Sugarbeet', amount: 5 }], utensil: 'Kitchen Knife', duration: 4 },
  { name: 'Burger Buns', station: 'cutting_board', ingredients: [{ name: 'Flour', amount: 5 }], utensil: 'Blender', duration: 4 },
  { name: 'Chicken Strips', station: 'cutting_board', ingredients: [{ name: 'Packaged Chicken', amount: 5 }], utensil: 'Meat Cleaver', duration: 4 },
  { name: 'Chicken Wings', station: 'cutting_board', ingredients: [{ name: 'Packaged Chicken', amount: 5 }], utensil: 'Meat Cleaver', duration: 4 },
  { name: 'Chopped Cabbage', station: 'cutting_board', ingredients: [{ name: 'Cabbage', amount: 5 }], utensil: 'Kitchen Knife', duration: 4 },
  { name: 'Chopped Carrot', station: 'cutting_board', ingredients: [{ name: 'Carrot', amount: 5 }], utensil: 'Kitchen Knife', duration: 4 },
  { name: 'Chopped Cucumber', station: 'cutting_board', ingredients: [{ name: 'Cucumber', amount: 5 }], utensil: 'Kitchen Knife', duration: 4 },
  { name: 'Chopped Red Pepper', station: 'cutting_board', ingredients: [{ name: 'Red Pepper', amount: 5 }], utensil: 'Kitchen Knife', duration: 4 },
  { name: 'Chopped Tomato', station: 'cutting_board', ingredients: [{ name: 'Tomato', amount: 5 }], utensil: 'Kitchen Knife', duration: 4 },
  { name: 'Corn On The Cob', station: 'cutting_board', ingredients: [{ name: 'Corn', amount: 5 }], utensil: 'Blender', duration: 4 },
  { name: 'Cooked Rice', station: 'cutting_board', ingredients: [{ name: 'Rice', amount: 5 }], utensil: 'Whisks', duration: 4 },
  { name: 'Cubbed Cheddar Cheese', station: 'cutting_board', ingredients: [{ name: 'Cheddar Cheese', amount: 5 }], utensil: 'Kitchen Knife', duration: 4 },
  { name: 'Cubed Mozzarella Cheese', station: 'cutting_board', ingredients: [{ name: 'Mozzarella Cheese', amount: 5 }], utensil: 'Kitchen Knife', duration: 4 },
  { name: 'Cut Lemon', station: 'cutting_board', ingredients: [{ name: 'Lemon', amount: 5 }], utensil: 'Kitchen Knife', duration: 4 },
  { name: 'Cut Orange', station: 'cutting_board', ingredients: [{ name: 'Orange', amount: 5 }], utensil: 'Kitchen Knife', duration: 4 },
  { name: 'Cut Poppy', station: 'cutting_board', ingredients: [{ name: 'Poppy', amount: 5 }], utensil: 'Kitchen Knife', duration: 4 },
  { name: 'Cut Strawberry', station: 'cutting_board', ingredients: [{ name: 'Strawberry', amount: 5 }], utensil: 'Kitchen Knife', duration: 4 },
  { name: 'Cut Watermelon', station: 'cutting_board', ingredients: [{ name: 'Watermelon', amount: 5 }], utensil: 'Kitchen Knife', duration: 4 },
  { name: 'Raw Beef Tenderloin', station: 'cutting_board', ingredients: [{ name: 'Raw Meat', amount: 5 }], utensil: 'Blender', duration: 4 },
  { name: 'Fish Fillet', station: 'cutting_board', ingredients: [{ name: 'Packaged Fish', amount: 5 }], utensil: 'Meat Cleaver', duration: 4 },
  { name: 'Flat Bread', station: 'cutting_board', ingredients: [{ name: 'Bread Loaf', amount: 5 }], utensil: 'Whisks', duration: 4 },
  { name: 'Flour', station: 'cutting_board', ingredients: [{ name: 'Wheat', amount: 5 }], utensil: 'Whisks', duration: 4 },
  { name: 'Garlic Powder', station: 'cutting_board', ingredients: [{ name: 'Garlic', amount: 5 }], utensil: 'Blender', duration: 4 },
  { name: 'Lasagna Noodles', station: 'cutting_board', ingredients: [{ name: 'Flour', amount: 5 }], utensil: 'Grater', duration: 4 },
  { name: 'Macaroni Noodles', station: 'cutting_board', ingredients: [{ name: 'Flour', amount: 5 }], utensil: 'Grater', duration: 4 },
  { name: 'Onion Powder', station: 'cutting_board', ingredients: [{ name: 'Onion', amount: 5 }], utensil: 'Blender', duration: 4 },
  { name: 'Pepper', station: 'cutting_board', ingredients: [{ name: 'Red Pepper', amount: 5 }], utensil: 'Blender', duration: 4 },
  { name: 'Sliced Potato', station: 'cutting_board', ingredients: [{ name: 'Potato', amount: 5 }], utensil: 'Slicer', duration: 4 },
  { name: 'Ramen Noodles', station: 'cutting_board', ingredients: [{ name: 'Flour', amount: 5 }], utensil: 'Grater', duration: 4 },
  { name: 'Roast Beef', station: 'cutting_board', ingredients: [{ name: 'Raw Meat', amount: 5 }], utensil: 'Blender', duration: 4 },
  { name: 'Sliced Red Pepper', station: 'cutting_board', ingredients: [{ name: 'Red Pepper', amount: 5 }], utensil: 'Slicer', duration: 4 },
  { name: 'Tomato Slices', station: 'cutting_board', ingredients: [{ name: 'Tomato', amount: 5 }], utensil: 'Slicer', duration: 4 },
  { name: 'String Cheddar Cheese', station: 'cutting_board', ingredients: [{ name: 'Cheddar Cheese', amount: 5 }], utensil: 'Grater', duration: 4 },
  { name: 'String Mozzarella Cheese', station: 'cutting_board', ingredients: [{ name: 'Mozzarella Cheese', amount: 5 }], utensil: 'Grater', duration: 4 },
  { name: 'Sugar', station: 'cutting_board', ingredients: [{ name: 'Sugarbeet', amount: 5 }], utensil: 'Blender', duration: 4 },

  // Fry Station (20 recipes) — JSON default_duration 8s, default_output 10, some have overrides
  { name: 'Kukituy', station: 'fry_station', ingredients: [{ name: 'Eggs', amount: 1 }, { name: 'Butter', amount: 1 }, { name: 'Flour', amount: 1 }, { name: 'Bread Loaf', amount: 1 }], duration: 8 },
  { name: 'Tahu Bulat', station: 'fry_station', ingredients: [{ name: 'Eggs', amount: 1 }, { name: 'Sliced Potato', amount: 1 }, { name: 'Flour', amount: 1 }, { name: 'Salt', amount: 1 }], duration: 8 },
  { name: 'Gorengan', station: 'fry_station', ingredients: [{ name: 'Eggs', amount: 1 }, { name: 'Sliced Potato', amount: 1 }, { name: 'Flour', amount: 1 }, { name: 'Salt', amount: 1 }], duration: 8 },
  { name: 'Nasi Kuning', station: 'fry_station', ingredients: [{ name: 'Eggs', amount: 1 }, { name: 'Sliced Potato', amount: 1 }, { name: 'Flour', amount: 1 }, { name: 'Salt', amount: 1 }], duration: 8 },
  { name: 'Sushi Platter', station: 'fry_station', ingredients: [{ name: 'Salt', amount: 1 }, { name: 'Sliced Potato', amount: 1 }, { name: 'Chicken Strips', amount: 1 }, { name: 'BBQ Sauce', amount: 1 }], duration: 8 },
  { name: 'Bakso', station: 'fry_station', ingredients: [{ name: 'Pepper', amount: 1 }, { name: 'Chili Powder', amount: 1 }, { name: 'Flour', amount: 1 }, { name: 'Chicken Wings', amount: 1 }], duration: 8 },
  { name: 'Spaghetti Aglio E Olio', station: 'fry_station', ingredients: [{ name: 'Eggs', amount: 1 }, { name: 'Ramen Noodles', amount: 1 }, { name: 'Flour', amount: 1 }, { name: 'Pepper', amount: 1 }], duration: 8 },
  { name: 'Zuppa Soup', station: 'fry_station', ingredients: [{ name: 'Flat Bread', amount: 1 }, { name: 'Garlic Powder', amount: 1 }, { name: 'Tomato Slices', amount: 1 }, { name: 'Chicken Wings', amount: 1 }], duration: 8 },
  { name: 'Mukidi Kove', station: 'fry_station', ingredients: [{ name: 'Pepper', amount: 1 }, { name: 'Chili Powder', amount: 1 }, { name: 'Flour', amount: 1 }, { name: 'Chicken Wings', amount: 1 }], duration: 8 },
  { name: 'Ayam Penyet Mas Jackson', station: 'fry_station', ingredients: [{ name: 'Eggs', amount: 1 }, { name: 'Sliced Potato', amount: 1 }, { name: 'Butter', amount: 1 }, { name: 'Bread Loaf', amount: 1 }, { name: 'Flour', amount: 1 }], duration: 10 },
  { name: 'Fajitas', station: 'fry_station', ingredients: [{ name: 'Burger Buns', amount: 1 }, { name: 'Chopped Cucumber', amount: 1 }, { name: 'Tomato Slices', amount: 1 }, { name: 'Chicken Wings', amount: 1 }], duration: 8 },
  { name: 'Tacos Al Pastor', station: 'fry_station', ingredients: [{ name: 'Butter', amount: 1 }, { name: 'Chili Powder', amount: 1 }, { name: 'Pepper', amount: 1 }, { name: 'Chicken Wings', amount: 1 }, { name: 'Flour', amount: 1 }], duration: 10 },
  { name: 'Albondigas', station: 'fry_station', ingredients: [{ name: 'Sliced Potato', amount: 1 }, { name: 'Cooked Rice', amount: 1 }, { name: 'Garlic Powder', amount: 1 }, { name: 'Raw Beef Tenderloin', amount: 1 }], duration: 8 },
  { name: 'Tostadas', station: 'fry_station', ingredients: [{ name: 'Eggs', amount: 1 }, { name: 'Mozzarella Cheese', amount: 1 }, { name: 'Chicken Strips', amount: 1 }, { name: 'Salt', amount: 1 }, { name: 'Macaroni Noodles', amount: 1 }], duration: 10 },
  { name: 'Chakalaka & PAP', station: 'fry_station', ingredients: [{ name: 'Eggs', amount: 1 }, { name: 'Sliced Potato', amount: 1 }, { name: 'Chicken Strips', amount: 1 }, { name: 'BBQ Sauce', amount: 1 }, { name: 'Chopped Tomato', amount: 1 }], duration: 10 },
  { name: 'Bouillabaisse', station: 'fry_station', ingredients: [{ name: 'Flat Bread', amount: 1 }, { name: 'Garlic Powder', amount: 1 }, { name: 'Tomato Slices', amount: 1 }, { name: 'Chicken Wings', amount: 1 }], duration: 8 },
  { name: 'Tira Miss You Cake', station: 'fry_station', ingredients: [{ name: 'Eggs', amount: 1 }, { name: 'Flour', amount: 1 }, { name: 'Butter', amount: 1 }], duration: 6 },
  { name: 'Martabak Aci Gulung', station: 'fry_station', ingredients: [{ name: 'Eggs', amount: 1 }, { name: 'Sliced Potato', amount: 1 }, { name: 'Butter', amount: 1 }, { name: 'Bread Loaf', amount: 1 }, { name: 'Flour', amount: 1 }], duration: 10 },
  { name: 'Limit & Lilis Fry', station: 'fry_station', ingredients: [{ name: 'Eggs', amount: 1 }, { name: 'Sliced Potato', amount: 1 }, { name: 'Butter', amount: 1 }, { name: 'Bread Loaf', amount: 1 }, { name: 'Flour', amount: 1 }], duration: 10 },
  { name: 'Mie Ayam Goat', station: 'fry_station', ingredients: [{ name: 'Burger Buns', amount: 1 }, { name: 'Chopped Cucumber', amount: 1 }, { name: 'Tomato Slices', amount: 1 }, { name: 'Chicken Wings', amount: 1 }], duration: 8 },
  { name: 'Macaroon', station: 'fry_station', ingredients: [{ name: 'Eggs', amount: 1 }, { name: 'Flat Bread', amount: 1 }, { name: 'Salt', amount: 1 }, { name: 'String Cheddar Cheese', amount: 1 }], duration: 8 },

  // Drink Station (52 recipes) — JSON default_duration 10s, some have 8s overrides
  { name: 'Red Velvet Coffee Latte', station: 'drink_station', ingredients: [{ name: 'Ice Cream', amount: 1 }, { name: 'Milk', amount: 1 }, { name: 'Brown Sugar', amount: 1 }, { name: 'Sugar', amount: 1 }, { name: 'Cut Lemon', amount: 1 }], duration: 10 },
  { name: 'Capucinno Latte', station: 'drink_station', ingredients: [{ name: 'Sugar', amount: 1 }, { name: 'Yogurt', amount: 1 }, { name: 'Ice Cream', amount: 1 }, { name: 'Cut Watermelon', amount: 1 }, { name: 'Brown Sugar', amount: 1 }], duration: 10 },
  { name: 'Caramel Macchiato', station: 'drink_station', ingredients: [{ name: 'Brown Sugar', amount: 1 }, { name: 'Cinnamon', amount: 1 }, { name: 'Sugar', amount: 1 }, { name: 'Milk', amount: 1 }], duration: 8 },
  { name: 'Hot Choco Milk', station: 'drink_station', ingredients: [{ name: 'Brown Sugar', amount: 1 }, { name: 'Cinnamon', amount: 1 }, { name: 'Milk', amount: 1 }, { name: 'Ice Cream', amount: 1 }], duration: 8 },
  { name: 'Milktuy', station: 'drink_station', ingredients: [{ name: 'Ice Cube', amount: 1 }, { name: 'Cut Lemon', amount: 1 }, { name: 'Milk', amount: 1 }, { name: 'Mint', amount: 1 }, { name: 'Yogurt', amount: 1 }], duration: 10 },
  { name: 'Berrysuy', station: 'drink_station', ingredients: [{ name: 'Ice Cube', amount: 1 }, { name: 'Cut Strawberry', amount: 1 }, { name: 'Sugar', amount: 1 }, { name: 'Milk', amount: 1 }], duration: 8 },
  { name: 'Es Teh Cekek', station: 'drink_station', ingredients: [{ name: 'Ice Cube', amount: 1 }, { name: 'Cut Lemon', amount: 1 }, { name: 'Sugar', amount: 1 }, { name: 'Soda', amount: 1 }, { name: 'Mint', amount: 1 }], duration: 10 },
  { name: 'Kopi Hitam', station: 'drink_station', ingredients: [{ name: 'Ice Cube', amount: 1 }, { name: 'Cut Lemon', amount: 1 }, { name: 'Sugar', amount: 1 }, { name: 'Soda', amount: 1 }, { name: 'Mint', amount: 1 }], duration: 10 },
  { name: 'Es Teh', station: 'drink_station', ingredients: [{ name: 'Ice Cube', amount: 1 }, { name: 'Cut Lemon', amount: 1 }, { name: 'Sugar', amount: 1 }, { name: 'Soda', amount: 1 }, { name: 'Mint', amount: 1 }], duration: 10 },
  { name: 'Ice Cream Strawberry', station: 'drink_station', ingredients: [{ name: 'Ice Cream', amount: 1 }, { name: 'Sugar', amount: 1 }, { name: 'Milk', amount: 1 }, { name: 'Cut Lemon', amount: 1 }, { name: 'Cut Strawberry', amount: 1 }], duration: 10 },
  { name: 'Long Black Coffee', station: 'drink_station', ingredients: [{ name: 'Brown Sugar', amount: 1 }, { name: 'Cinnamon', amount: 1 }, { name: 'Milk', amount: 1 }, { name: 'Ice Cream', amount: 1 }], duration: 8 },
  { name: 'Ice Cream Cokelat Strawberry', station: 'drink_station', ingredients: [{ name: 'Ice Cream', amount: 1 }, { name: 'Sugar', amount: 1 }, { name: 'Milk', amount: 1 }, { name: 'Cut Lemon', amount: 1 }, { name: 'Cut Strawberry', amount: 1 }], duration: 10 },
  { name: 'Spongnya Ichigo Frappe', station: 'drink_station', ingredients: [{ name: 'Ice Cream', amount: 1 }, { name: 'Milk', amount: 1 }, { name: 'Brown Sugar', amount: 1 }, { name: 'Sugar', amount: 1 }, { name: 'Cut Lemon', amount: 1 }], duration: 10 },
  { name: 'Coconut Limade', station: 'drink_station', ingredients: [{ name: 'Brown Sugar', amount: 1 }, { name: 'Cinnamon', amount: 1 }, { name: 'Milk', amount: 1 }, { name: 'Ice Cream', amount: 1 }], duration: 8 },
  { name: 'Black Tea', station: 'drink_station', ingredients: [{ name: 'Cinnamon', amount: 1 }, { name: 'Sugar', amount: 1 }, { name: 'Brown Sugar', amount: 1 }, { name: 'Milk', amount: 1 }, { name: 'Yogurt', amount: 1 }], duration: 10 },
  { name: 'Jus Mengkudu', station: 'drink_station', ingredients: [{ name: 'Ice Cube', amount: 1 }, { name: 'Cut Lemon', amount: 1 }, { name: 'Milk', amount: 1 }, { name: 'Mint', amount: 1 }, { name: 'Yogurt', amount: 1 }], duration: 10 },
  { name: 'Es Jeruk', station: 'drink_station', ingredients: [{ name: 'Ice Cube', amount: 1 }, { name: 'Ice Cream', amount: 1 }, { name: 'Cut Lemon', amount: 1 }, { name: 'Milk', amount: 1 }, { name: 'Sugar', amount: 1 }], duration: 10 },
  { name: 'Red Rooibos', station: 'drink_station', ingredients: [{ name: 'Cinnamon', amount: 1 }, { name: 'Yogurt', amount: 1 }, { name: 'Milk', amount: 1 }, { name: 'Cut Strawberry', amount: 1 }, { name: 'Sugar', amount: 1 }], duration: 10 },
  { name: 'Ice Coklat', station: 'drink_station', ingredients: [{ name: 'Milk', amount: 1 }, { name: 'Yogurt', amount: 1 }, { name: 'Mint', amount: 1 }, { name: 'Sugar', amount: 1 }, { name: 'Ice Cube', amount: 1 }], duration: 10 },
  { name: 'Ice Lemon Tea', station: 'drink_station', ingredients: [{ name: 'Cut Strawberry', amount: 1 }, { name: 'Ice Cube', amount: 1 }, { name: 'Soda', amount: 1 }, { name: 'Cut Watermelon', amount: 1 }], duration: 8 },
  { name: 'Ice Cream Vanilla', station: 'drink_station', ingredients: [{ name: 'Cut Lemon', amount: 1 }, { name: 'Ice Cube', amount: 1 }, { name: 'Milk', amount: 1 }, { name: 'Cut Strawberry', amount: 1 }, { name: 'Sugar', amount: 1 }], duration: 10 },
  { name: 'Jasmine Milk Creamy', station: 'drink_station', ingredients: [{ name: 'Cut Lemon', amount: 1 }, { name: 'Soda', amount: 1 }, { name: 'Cut Strawberry', amount: 1 }, { name: 'Sugar', amount: 1 }, { name: 'Ice Cube', amount: 1 }], duration: 10 },
  { name: 'Kolave', station: 'drink_station', ingredients: [{ name: 'Cut Lemon', amount: 1 }, { name: 'Soda', amount: 1 }, { name: 'Mint', amount: 1 }, { name: 'Sugar', amount: 1 }, { name: 'Ice Cube', amount: 1 }], duration: 10 },
  { name: 'Iced Biscoff Creamy Milk', station: 'drink_station', ingredients: [{ name: 'Cut Lemon', amount: 1 }, { name: 'Milk', amount: 1 }, { name: 'Brown Sugar', amount: 1 }, { name: 'Ice Cube', amount: 1 }, { name: 'Sugar', amount: 1 }], duration: 10 },
  { name: 'Sakura Jasmine Peach', station: 'drink_station', ingredients: [{ name: 'Cinnamon', amount: 1 }, { name: 'Yogurt', amount: 1 }, { name: 'Milk', amount: 1 }, { name: 'Cut Strawberry', amount: 1 }, { name: 'Sugar', amount: 1 }], duration: 10 },
  { name: 'Ice Cream Matcha', station: 'drink_station', ingredients: [{ name: 'Ice Cream', amount: 1 }, { name: 'Sugar', amount: 1 }, { name: 'Milk', amount: 1 }, { name: 'Cut Lemon', amount: 1 }, { name: 'Cut Strawberry', amount: 1 }], duration: 10 },
  { name: '30 Nights Milk', station: 'drink_station', ingredients: [{ name: 'Cut Lemon', amount: 1 }, { name: 'Ice Cube', amount: 1 }, { name: 'Mint', amount: 1 }, { name: 'Brown Sugar', amount: 1 }, { name: 'Sugar', amount: 1 }], duration: 10 },
  { name: 'Hot Choco Jackson Edition', station: 'drink_station', ingredients: [{ name: 'Cut Lemon', amount: 1 }, { name: 'Ice Cube', amount: 1 }, { name: 'Mint', amount: 1 }, { name: 'Brown Sugar', amount: 1 }, { name: 'Sugar', amount: 1 }], duration: 10 },
  { name: 'Ice Cream Lele', station: 'drink_station', ingredients: [{ name: 'Cut Lemon', amount: 1 }, { name: 'Ice Cube', amount: 1 }, { name: 'Mint', amount: 1 }, { name: 'Brown Sugar', amount: 1 }, { name: 'Sugar', amount: 1 }], duration: 10 },
  { name: 'C&O Cola', station: 'drink_station', ingredients: [{ name: 'Cut Lemon', amount: 1 }, { name: 'Yogurt', amount: 1 }, { name: 'Brown Sugar', amount: 1 }, { name: 'Ice Cube', amount: 1 }, { name: 'Sugar', amount: 1 }], duration: 10 },
  { name: 'Cocacino', station: 'drink_station', ingredients: [{ name: 'Cut Lemon', amount: 1 }, { name: 'Ice Cube', amount: 1 }, { name: 'Mint', amount: 1 }, { name: 'Brown Sugar', amount: 1 }, { name: 'Sugar', amount: 1 }], duration: 10 },
  { name: 'Iced Berry Manuka Americano', station: 'drink_station', ingredients: [{ name: 'Cut Strawberry', amount: 1 }, { name: 'Cut Watermelon', amount: 1 }, { name: 'Mint', amount: 1 }, { name: 'Sugar', amount: 1 }, { name: 'Ice Cube', amount: 1 }], duration: 10 },
  { name: 'Blue Lemon Soda', station: 'drink_station', ingredients: [{ name: 'Cut Lemon', amount: 1 }, { name: 'Soda', amount: 1 }, { name: 'Brown Sugar', amount: 1 }, { name: 'Ice Cube', amount: 1 }, { name: 'Sugar', amount: 1 }], duration: 10 },
  { name: 'Mango Yakult Fizz', station: 'drink_station', ingredients: [{ name: 'Soda', amount: 1 }, { name: 'Cut Watermelon', amount: 1 }, { name: 'Mint', amount: 1 }, { name: 'Cut Orange', amount: 1 }, { name: 'Sugar', amount: 1 }], duration: 10 },
  { name: 'Strawberry Matcha Fusion', station: 'drink_station', ingredients: [{ name: 'Soda', amount: 1 }, { name: 'Cut Watermelon', amount: 1 }, { name: 'Cut Strawberry', amount: 1 }, { name: 'Sugar', amount: 1 }, { name: 'Ice Cube', amount: 1 }], duration: 10 },
  { name: 'Montblanc Creamy Latte', station: 'drink_station', ingredients: [{ name: 'Soda', amount: 1 }, { name: 'Cut Orange', amount: 1 }, { name: 'Cut Strawberry', amount: 1 }, { name: 'Cinnamon', amount: 1 }, { name: 'Sugar', amount: 1 }], duration: 10 },
  { name: 'Purple Butterfly Pea Lemonade', station: 'drink_station', ingredients: [{ name: 'Cut Lemon', amount: 1 }, { name: 'Soda', amount: 1 }, { name: 'Cut Strawberry', amount: 1 }, { name: 'Sugar', amount: 1 }, { name: 'Ice Cube', amount: 1 }], duration: 10 },
  { name: 'Limit & Lilis Choco', station: 'drink_station', ingredients: [{ name: 'Cut Lemon', amount: 1 }, { name: 'Ice Cube', amount: 1 }, { name: 'Mint', amount: 1 }, { name: 'Brown Sugar', amount: 1 }, { name: 'Sugar', amount: 1 }], duration: 10 },
  { name: 'Energy Major', station: 'drink_station', ingredients: [{ name: 'Cut Lemon', amount: 1 }, { name: 'Ice Cube', amount: 1 }, { name: 'Mint', amount: 1 }, { name: 'Brown Sugar', amount: 1 }, { name: 'Sugar', amount: 1 }], duration: 10 },
  { name: 'Limit & Lilis Strawberry', station: 'drink_station', ingredients: [{ name: 'Cut Lemon', amount: 1 }, { name: 'Ice Cube', amount: 1 }, { name: 'Mint', amount: 1 }, { name: 'Brown Sugar', amount: 1 }, { name: 'Sugar', amount: 1 }], duration: 10 },
  { name: 'Ice Lychee Tea 1', station: 'drink_station', ingredients: [{ name: 'Cut Lemon', amount: 1 }, { name: 'Ice Cube', amount: 1 }, { name: 'Mint', amount: 1 }, { name: 'Brown Sugar', amount: 1 }, { name: 'Sugar', amount: 1 }], duration: 10 },
  { name: 'Es Jeruk Segar', station: 'drink_station', ingredients: [{ name: 'Cut Lemon', amount: 1 }, { name: 'Ice Cube', amount: 1 }, { name: 'Mint', amount: 1 }, { name: 'Brown Sugar', amount: 1 }, { name: 'Sugar', amount: 1 }], duration: 10 },
  { name: 'Lilis & Ningsih Lemonade', station: 'drink_station', ingredients: [{ name: 'Cut Lemon', amount: 1 }, { name: 'Ice Cube', amount: 1 }, { name: 'Mint', amount: 1 }, { name: 'Brown Sugar', amount: 1 }, { name: 'Sugar', amount: 1 }], duration: 10 },
  { name: 'Benchy Strawberry Milk', station: 'drink_station', ingredients: [{ name: 'Cut Lemon', amount: 1 }, { name: 'Ice Cube', amount: 1 }, { name: 'Mint', amount: 1 }, { name: 'Brown Sugar', amount: 1 }, { name: 'Sugar', amount: 1 }], duration: 10 },
  { name: 'Iced Matcha Strawberry Latte', station: 'drink_station', ingredients: [{ name: 'Cut Lemon', amount: 1 }, { name: 'Ice Cube', amount: 1 }, { name: 'Mint', amount: 1 }, { name: 'Brown Sugar', amount: 1 }, { name: 'Sugar', amount: 1 }], duration: 10 },
  { name: 'Yerba Mate Goat', station: 'drink_station', ingredients: [{ name: 'Cut Strawberry', amount: 1 }, { name: 'Cut Watermelon', amount: 1 }, { name: 'Mint', amount: 1 }, { name: 'Sugar', amount: 1 }, { name: 'Ice Cube', amount: 1 }], duration: 10 },
  { name: 'Ice Lychee Tea 2', station: 'drink_station', ingredients: [{ name: 'Cut Lemon', amount: 1 }, { name: 'Ice Cube', amount: 1 }, { name: 'Mint', amount: 1 }, { name: 'Brown Sugar', amount: 1 }, { name: 'Sugar', amount: 1 }], duration: 10 },
  { name: 'Monna Ice Coffe', station: 'drink_station', ingredients: [{ name: 'Cut Lemon', amount: 1 }, { name: 'Ice Cube', amount: 1 }, { name: 'Mint', amount: 1 }, { name: 'Brown Sugar', amount: 1 }, { name: 'Sugar', amount: 1 }], duration: 10 },
  { name: 'Sobi Smothies', station: 'drink_station', ingredients: [{ name: 'Cut Lemon', amount: 1 }, { name: 'Ice Cube', amount: 1 }, { name: 'Mint', amount: 1 }, { name: 'Brown Sugar', amount: 1 }, { name: 'Sugar', amount: 1 }], duration: 10 },
  { name: 'Milkshake Vanilla Glencin', station: 'drink_station', ingredients: [{ name: 'Cut Lemon', amount: 1 }, { name: 'Ice Cube', amount: 1 }, { name: 'Mint', amount: 1 }, { name: 'Brown Sugar', amount: 1 }, { name: 'Sugar', amount: 1 }], duration: 10 },
  { name: 'Es The Gracek', station: 'drink_station', ingredients: [{ name: 'Cut Lemon', amount: 1 }, { name: 'Ice Cube', amount: 1 }, { name: 'Mint', amount: 1 }, { name: 'Brown Sugar', amount: 1 }, { name: 'Sugar', amount: 1 }], duration: 10 },
  { name: 'Milkshake Strawberry With Love', station: 'drink_station', ingredients: [{ name: 'Cut Lemon', amount: 1 }, { name: 'Ice Cube', amount: 1 }, { name: 'Mint', amount: 1 }, { name: 'Brown Sugar', amount: 1 }, { name: 'Sugar', amount: 1 }], duration: 10 },

  // Stove (39 recipes) — JSON default_duration 10s, some have 8s or 6s overrides
  { name: 'Macaroon', station: 'stove', ingredients: [{ name: 'Burger Buns', amount: 1 }, { name: 'Flour', amount: 1 }, { name: 'Eggs', amount: 1 }, { name: 'Butter', amount: 1 }], duration: 8 },
  { name: 'Cheesecake Strawberry', station: 'stove', ingredients: [{ name: 'Flat Bread', amount: 1 }, { name: 'Salt', amount: 1 }, { name: 'Eggs', amount: 1 }, { name: 'Butter', amount: 1 }, { name: 'String Cheddar Cheese', amount: 1 }], duration: 10 },
  { name: 'Ginger Cookies', station: 'stove', ingredients: [{ name: 'Flour', amount: 1 }, { name: 'Flat Bread', amount: 1 }, { name: 'Butter', amount: 1 }], duration: 6 },
  { name: 'Kukituy', station: 'stove', ingredients: [{ name: 'Bread Loaf', amount: 1 }, { name: 'Flour', amount: 1 }, { name: 'Eggs', amount: 1 }, { name: 'Butter', amount: 1 }], duration: 8 },
  { name: 'Dorasuy', station: 'stove', ingredients: [{ name: 'Burger Buns', amount: 1 }, { name: 'Flour', amount: 1 }, { name: 'Eggs', amount: 1 }, { name: 'Butter', amount: 1 }], duration: 8 },
  { name: 'Nailong', station: 'stove', ingredients: [{ name: 'Bread Loaf', amount: 1 }, { name: 'Butter', amount: 1 }, { name: 'Eggs', amount: 1 }, { name: 'Flour', amount: 1 }, { name: 'Chicken Wings', amount: 1 }], duration: 10 },
  { name: 'Sushi Platter', station: 'stove', ingredients: [{ name: 'Sliced Potato', amount: 1 }, { name: 'BBQ Sauce', amount: 1 }, { name: 'Chicken Strips', amount: 1 }, { name: 'Salt', amount: 1 }], duration: 8 },
  { name: 'Puding Lele', station: 'stove', ingredients: [{ name: 'Bread Loaf', amount: 1 }, { name: 'Flour', amount: 1 }, { name: 'Eggs', amount: 1 }], duration: 6 },
  { name: 'Pain Au Chocolat', station: 'stove', ingredients: [{ name: 'Flour', amount: 1 }, { name: 'Flat Bread', amount: 1 }, { name: 'Butter', amount: 1 }], duration: 6 },
  { name: 'Cokelat Bucket Strawberry', station: 'stove', ingredients: [{ name: 'Burger Buns', amount: 1 }, { name: 'Butter', amount: 1 }, { name: 'Eggs', amount: 1 }, { name: 'String Cheddar Cheese', amount: 1 }, { name: 'Salt', amount: 1 }], duration: 10 },
  { name: 'Suplli', station: 'stove', ingredients: [{ name: 'Eggs', amount: 1 }, { name: 'Flat Bread', amount: 1 }, { name: 'Salt', amount: 1 }, { name: 'String Cheddar Cheese', amount: 1 }], duration: 8 },
  { name: 'Caesar Salad', station: 'stove', ingredients: [{ name: 'Bread Loaf', amount: 1 }, { name: 'Flour', amount: 1 }, { name: 'Eggs', amount: 1 }, { name: 'Butter', amount: 1 }], duration: 8 },
  { name: 'Cokelat Dubai', station: 'stove', ingredients: [{ name: 'Bread Loaf', amount: 1 }, { name: 'Flour', amount: 1 }, { name: 'Eggs', amount: 1 }, { name: 'Burger Buns', amount: 1 }], duration: 8 },
  { name: 'Dubai Chewy Mochii', station: 'stove', ingredients: [{ name: 'Burger Buns', amount: 1 }, { name: 'String Cheddar Cheese', amount: 1 }, { name: 'Eggs', amount: 1 }, { name: 'Flour', amount: 1 }, { name: 'Butter', amount: 1 }], duration: 10 },
  { name: 'Cookies Glen', station: 'stove', ingredients: [{ name: 'Bread Loaf', amount: 1 }, { name: 'Flour', amount: 1 }, { name: 'Eggs', amount: 1 }, { name: 'Butter', amount: 1 }], duration: 8 },
  { name: 'Cake Red Velvet', station: 'stove', ingredients: [{ name: 'Flat Bread', amount: 1 }, { name: 'Salt', amount: 1 }, { name: 'Eggs', amount: 1 }, { name: 'Butter', amount: 1 }, { name: 'String Cheddar Cheese', amount: 1 }], duration: 10 },
  { name: 'Pudding Lovely Bears', station: 'stove', ingredients: [{ name: 'Burger Buns', amount: 1 }, { name: 'Butter', amount: 1 }, { name: 'Eggs', amount: 1 }, { name: 'String Cheddar Cheese', amount: 1 }, { name: 'Flour', amount: 1 }], duration: 10 },
  { name: 'Lovey-Dovey Donuts', station: 'stove', ingredients: [{ name: 'Burger Buns', amount: 1 }, { name: 'Butter', amount: 1 }, { name: 'Eggs', amount: 1 }, { name: 'String Cheddar Cheese', amount: 1 }, { name: 'Flour', amount: 1 }], duration: 10 },
  { name: 'Spongnya Ichigo Shortcakes', station: 'stove', ingredients: [{ name: 'Eggs', amount: 1 }, { name: 'Flat Bread', amount: 1 }, { name: 'Salt', amount: 1 }, { name: 'String Cheddar Cheese', amount: 1 }], duration: 8 },
  { name: 'Thirty Bites Cookies', station: 'stove', ingredients: [{ name: 'Bread Loaf', amount: 1 }, { name: 'Butter', amount: 1 }, { name: 'Sliced Potato', amount: 1 }, { name: 'Eggs', amount: 1 }, { name: 'Flour', amount: 1 }], duration: 10 },
  { name: 'Cookies Winterfeld', station: 'stove', ingredients: [{ name: 'Bread Loaf', amount: 1 }, { name: 'Butter', amount: 1 }, { name: 'Sliced Potato', amount: 1 }, { name: 'Eggs', amount: 1 }, { name: 'Flour', amount: 1 }], duration: 10 },
  { name: 'Ckove', station: 'stove', ingredients: [{ name: 'Bread Loaf', amount: 1 }, { name: 'Butter', amount: 1 }, { name: 'Sliced Potato', amount: 1 }, { name: 'Eggs', amount: 1 }, { name: 'Flour', amount: 1 }], duration: 10 },
  { name: 'Dead County MC', station: 'stove', ingredients: [{ name: 'Bread Loaf', amount: 1 }, { name: 'Butter', amount: 1 }, { name: 'Sliced Potato', amount: 1 }, { name: 'Eggs', amount: 1 }, { name: 'Flour', amount: 1 }], duration: 10 },
  { name: 'Cheese Burger', station: 'stove', ingredients: [{ name: 'Bread Loaf', amount: 1 }, { name: 'Butter', amount: 1 }, { name: 'Sliced Potato', amount: 1 }, { name: 'Eggs', amount: 1 }, { name: 'Flour', amount: 1 }], duration: 10 },
  { name: 'My Beautiful Burger', station: 'stove', ingredients: [{ name: 'Bread Loaf', amount: 1 }, { name: 'Butter', amount: 1 }, { name: 'Sliced Potato', amount: 1 }, { name: 'Eggs', amount: 1 }, { name: 'Flour', amount: 1 }], duration: 10 },
  { name: 'C&O Sweet & Buttery Popcorn', station: 'stove', ingredients: [{ name: 'Bread Loaf', amount: 1 }, { name: 'Butter', amount: 1 }, { name: 'Sliced Potato', amount: 1 }, { name: 'Eggs', amount: 1 }, { name: 'Flour', amount: 1 }], duration: 10 },
  { name: 'Dubai Cookies', station: 'stove', ingredients: [{ name: 'Bread Loaf', amount: 1 }, { name: 'Butter', amount: 1 }, { name: 'Sliced Potato', amount: 1 }, { name: 'Eggs', amount: 1 }, { name: 'Flour', amount: 1 }], duration: 10 },
  { name: 'Limit & Lilis Stove', station: 'stove', ingredients: [{ name: 'Bread Loaf', amount: 1 }, { name: 'Sliced Potato', amount: 1 }, { name: 'Butter', amount: 1 }, { name: 'Flour', amount: 1 }], duration: 10 },
  { name: 'Salmon Sushi Platter', station: 'stove', ingredients: [{ name: 'Bread Loaf', amount: 1 }, { name: 'Butter', amount: 1 }, { name: 'Sliced Potato', amount: 1 }, { name: 'Eggs', amount: 1 }, { name: 'Flour', amount: 1 }], duration: 10 },
  { name: 'Ayam Nashville', station: 'stove', ingredients: [{ name: 'Bread Loaf', amount: 1 }, { name: 'Butter', amount: 1 }, { name: 'Sliced Potato', amount: 1 }, { name: 'Eggs', amount: 1 }, { name: 'Flour', amount: 1 }], duration: 10 },
  { name: 'Lilis & Ningsih Ramen', station: 'stove', ingredients: [{ name: 'Bread Loaf', amount: 1 }, { name: 'Butter', amount: 1 }, { name: 'Sliced Potato', amount: 1 }, { name: 'Eggs', amount: 1 }, { name: 'Flour', amount: 1 }], duration: 10 },
  { name: 'Benchy Cookies', station: 'stove', ingredients: [{ name: 'Bread Loaf', amount: 1 }, { name: 'Butter', amount: 1 }, { name: 'Sliced Potato', amount: 1 }, { name: 'Eggs', amount: 1 }, { name: 'Flour', amount: 1 }], duration: 10 },
  { name: 'Ayam Hitam Madura', station: 'stove', ingredients: [{ name: 'Bread Loaf', amount: 1 }, { name: 'Butter', amount: 1 }, { name: 'Sliced Potato', amount: 1 }, { name: 'Eggs', amount: 1 }, { name: 'Flour', amount: 1 }], duration: 10 },
  { name: 'Spaghetti Aglio Oliove', station: 'stove', ingredients: [{ name: 'Bread Loaf', amount: 1 }, { name: 'Butter', amount: 1 }, { name: 'Sliced Potato', amount: 1 }, { name: 'Eggs', amount: 1 }, { name: 'Flour', amount: 1 }], duration: 10 },
  { name: 'Cookies Monna', station: 'stove', ingredients: [{ name: 'Bread Loaf', amount: 1 }, { name: 'Butter', amount: 1 }, { name: 'Sliced Potato', amount: 1 }, { name: 'Eggs', amount: 1 }, { name: 'Flour', amount: 1 }], duration: 10 },
  { name: 'Sobi Cookies', station: 'stove', ingredients: [{ name: 'Bread Loaf', amount: 1 }, { name: 'Butter', amount: 1 }, { name: 'Sliced Potato', amount: 1 }, { name: 'Eggs', amount: 1 }, { name: 'Flour', amount: 1 }], duration: 10 },
  { name: 'Katsu Glencin', station: 'stove', ingredients: [{ name: 'Bread Loaf', amount: 1 }, { name: 'Butter', amount: 1 }, { name: 'Sliced Potato', amount: 1 }, { name: 'Eggs', amount: 1 }, { name: 'Flour', amount: 1 }], duration: 10 },
  { name: 'Nasi Goreng Maiaria', station: 'stove', ingredients: [{ name: 'Bread Loaf', amount: 1 }, { name: 'Butter', amount: 1 }, { name: 'Sliced Potato', amount: 1 }, { name: 'Eggs', amount: 1 }, { name: 'Flour', amount: 1 }], duration: 10 },
  { name: 'Baked With Love', station: 'stove', ingredients: [{ name: 'Bread Loaf', amount: 1 }, { name: 'Butter', amount: 1 }, { name: 'Sliced Potato', amount: 1 }, { name: 'Eggs', amount: 1 }, { name: 'Flour', amount: 1 }], duration: 10 },
]

export const foodRecipes = recipes.filter(r => r.station !== 'drink_station')
export const drinkRecipes = recipes.filter(r => r.station === 'drink_station')

export function searchRecipes(query: string, station?: string): Recipe[] {
  const q = query.toLowerCase()
  return recipes.filter(r => {
    const matchesQuery = r.name.toLowerCase().includes(q) ||
      r.ingredients?.some(i => i.name.toLowerCase().includes(q))
    const matchesStation = !station || r.station === station
    return matchesQuery && matchesStation
  })
}
